first_day: 151
rank: 5
length: 5
tensor_shape: [482, 406, 93]
decomposition_method: PARAFAC
nitemax: 100
random_seed: 2434311
val_size: 0.045
logs: './test/reconstruction_logs'
refit: True
lat_lon_sep_centering: False 

satellite_descriptor: '/home/kulikov/dineof3/test/satellite_descriptor.csv' 
input_stem: Input
output_stem: Output
static_grid_stem: static_grid
interpolated_stem: interpolated
unified_tensor_stem: unified_tensor
timeline_stem: timeline
only_years: null
